### ISSUE TITLE
Setup GitHub Pages deployment without using github-pages gem

### ISSUE THREAD

**Issue by phrdang** [berkeley-cdss/berkeley-class-site#26]
As of #20 , the github-pages gem has been removed from the Gemfile list of dependencies, which is good because this allows us to use custom plugins and plugins that are not whitelisted by the github-pages gem.

However this means we need to figure out how we are going to deploy the site without using the nice GitHub Pages/Jekyll integration. From preliminary research, it seems the way to do this is to check into git the `_site` directory and deploy the html generated there, but the repository needs to be configured as does the CI workflow (jekyll.yml may not work anymore).

Potential resources to look into:

- https://github.com/actions/jekyll-build-pages
- https://github.com/jeffreytse/jekyll-deploy-action
- https://www.yegor256.com/2014/06/24/jekyll-github-deploy.html
- https://jekyllrb.com/docs/plugins/installation/ (see "Plugins on GitHub Pages" section)

**Comment by cycomachead** [comment]
AFAIK, the default pages deploy workflow file works just fine to do the deployment. 
It seems to be work already. :) 

The jekyll.yml still builds the site and was generated by GitHub. 

https://github.com/berkeley-eecs/berkeley-class-site/blob/main/.github/workflows/jekyll.yml
https://berkeley-eecs.github.io/berkeley-class-site/

Maybe we should edit the readme incase folks find the public site.

**Comment by cycomachead** [comment]
You can also verify here that thing work: https://github.com/berkeley-eecs/berkeley-class-site/deployments/github-pages

**Comment by phrdang** [comment]
Oh lol thanks for the catch, I just assumed it wouldn't work because of the jekyll plugin docs. I'll close this issue then!
